// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230822183355_firstmigrate")]
    partial class firstmigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domian.Entities.AddDueDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FinishedTime")
                        .HasColumnType("int");

                    b.Property<int>("TaskBaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskBaseId");

                    b.ToTable("AddDueDates");
                });

            modelBuilder.Entity("Domian.Entities.AddFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskBaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskBaseId");

                    b.ToTable("AddFiles");
                });

            modelBuilder.Entity("Domian.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddDateTime")
                        .HasColumnType("int");

                    b.Property<int>("TaskBaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskBaseId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Domian.Entities.RepeatTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddDateTime")
                        .HasColumnType("int");

                    b.Property<int>("Nummer")
                        .HasColumnType("int");

                    b.Property<int>("TaskBaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskBaseId");

                    b.ToTable("RepeatTimes");
                });

            modelBuilder.Entity("Domian.Entities.TaskBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FinishedTask")
                        .HasColumnType("bit");

                    b.Property<bool?>("Important")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Planned")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Remind_me")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Domian.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domian.Entities.AddDueDate", b =>
                {
                    b.HasOne("Domian.Entities.TaskBase", "TaskBase")
                        .WithMany("AddDueDates")
                        .HasForeignKey("TaskBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskBase");
                });

            modelBuilder.Entity("Domian.Entities.AddFile", b =>
                {
                    b.HasOne("Domian.Entities.TaskBase", "TaskBase")
                        .WithMany("AddFiles")
                        .HasForeignKey("TaskBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskBase");
                });

            modelBuilder.Entity("Domian.Entities.Category", b =>
                {
                    b.HasOne("Domian.Entities.TaskBase", "TaskBase")
                        .WithMany("Categories")
                        .HasForeignKey("TaskBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskBase");
                });

            modelBuilder.Entity("Domian.Entities.RepeatTime", b =>
                {
                    b.HasOne("Domian.Entities.TaskBase", "TaskBase")
                        .WithMany("RepeatTimes")
                        .HasForeignKey("TaskBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskBase");
                });

            modelBuilder.Entity("Domian.Entities.TaskBase", b =>
                {
                    b.HasOne("Domian.Entities.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domian.Entities.TaskBase", b =>
                {
                    b.Navigation("AddDueDates");

                    b.Navigation("AddFiles");

                    b.Navigation("Categories");

                    b.Navigation("RepeatTimes");
                });

            modelBuilder.Entity("Domian.Entities.User", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
